image: python:2.7

before_script:
  - apt-get update
  - apt-get install -y cmake liblz4-dev cython
  - pip install numpy matplotlib pandas scikit-hep ipython uproot lz4

build:
  script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make install
