matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      language: cpp
      services:
        - docker
      script:
        - docker build -t hipopy . -f docker/Dockerfile.py2
        - docker images -a
