matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      language: cpp
      services:
        - docker
      script:
        - docker build -t hipopy . -f docker/Dockerfile.py2
        - docker images -a
    - os: linux
      sudo: true
      dist: trusty
      language: cpp
      before_install:
        - sudo apt-get install -y liblz4-dev cython
      addons:
        apt:
          update: true
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j$(nproc)
    - os: osx
      language: cpp
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      script:
        - export SOURCE=$PWD
        - brew install lz4; echo "Done"
        - pip install cython scikit-build numpy
        - mkdir build && cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=$SOURCE/install
        - make
        - make install
