FROM alpine:3.8

RUN apk add --no-cache make g++ gcc cmake lz4-dev python2-dev && \
    python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools ipython numpy cython && \
    rm -r /root/.cache

COPY . /usr/source/hipopy
WORKDIR /usr/source/hipopy

ENV LD_LIBRARY_PATH /usr/local/lib
ENV PYTHONPATH /usr/local/lib

RUN mkdir -p build && cd build && cmake .. && make && make install

WORKDIR /tmp
ENTRYPOINT ["ipython"]
