FROM rootproject/root-ubuntu16

USER root

RUN apt-get update \
    && apt-get install -y liblz4-dev python-pip python-numpy \
    && rm -rf /var/lib/apt/lists/* \
    && pip install cython ipython==5.8.0

COPY . /usr/source/hipopy
WORKDIR /usr/source/hipopy

ENV LD_LIBRARY_PATH /usr/local/lib
ENV PYTHONPATH /usr/local/lib

RUN mkdir -p build && cd build && cmake .. && make && make install

WORKDIR /tmp
ENTRYPOINT ["ipython"]
